apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.deckhouse.io
  labels:
    heritage: deckhouse
    module: user-authn
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: groups
    singular: group
    kind: Group
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema: &schema
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Contains information about a user group.
              required:
                - members
              properties:
                members:
                  type: array
                  items:
                    type: object
                    required:
                      - kind
                      - name
                    properties:
                      kind:
                        type: string
                        description: Object type.
                        enum:
                          - User
                          - Group
                      name:
                        type: string
                        description: User or group name.
                status:
                  type: object
                  required: []
                  properties:
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          message:
                            type: string
                          objectRef:
                            type: object
                            properties:
                              kind:
                                type: string
                                enum:
                                  - User
                                  - Group
                              name:
                                type: string
