---
apiVersion: v1
kind: Secret
metadata:
  name: cacerts
  namespace: d8-istio
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: istio.io/ca-root
data:
  ca-cert.pem:    {{ .Values.istio.internal.ca.cert  | b64enc | quote }}
  ca-key.pem:     {{ .Values.istio.internal.ca.key   | b64enc | quote }}
  cert-chain.pem: {{ .Values.istio.internal.ca.chain | b64enc | quote }}
  root-cert.pem:  {{ .Values.istio.internal.ca.root  | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-remote-authn-keypair
  namespace: d8-istio
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
data:
  pub.pem: {{ .Values.istio.internal.remoteAuthnKeypair.pub | b64enc | quote }}
  priv.pem: {{ .Values.istio.internal.remoteAuthnKeypair.priv | b64enc | quote }}
