{{- if or .Values.istio.federation.enabled .Values.istio.multicluster.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-exporter
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "metadata-exporter")) | nindent 2 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
  selector:
    app: metadata-exporter
{{- end }}
