apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.deckhouse.io
  labels:
    heritage: deckhouse
    module: deckhouse
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: modules
    singular: module
    kind: Module
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines the configuration for Deckhouse module.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - version
              properties:
                name:
                  type: string
                  example: 'v1.24.20'
                foo:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}
