# baseURL = ""
title = "Kubernetes Documentation"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = false
disableBrowserError = true
disableLanguages = ['fr', 'zh-cn', 'ko', 'it', 'no', 'de', 'es', 'pt-br', 'id', 'hi', 'vi', 'pl', 'uk', 'ja', 'no']

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "home", "term", "robotsTXT", "404"]

ignoreFiles = [ "(?:^|/)OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = "180s"

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = false

relativeURLs = true

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     definitionList = true
     table = true
     typographer = false
   [markup.goldmark.parser]
     attribute = true
     autoHeadingID = true
     autoHeadingIDType = "blackfriday"
   [markup.goldmark.renderer]
     unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
page = [ "HTML"]
list = [ "HTML"]

# markdown file output
[outputFormats.MARKDOWN]
#baseName = "markdown"
isPlainText = true
#path = "markdown"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
id = "UA-00000000-0"

[params]
copyright_k8s = "The Kubernetes Authors"
copyright_linux = "Copyright © 2020 The Linux Foundation ®."

# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Versions"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM PST"

description = "Production-Grade Container Orchestration"
showedit = true

latest = "v1.26"

fullversion = "v1.26.0"
version = "v1.26"
githubbranch = "main"
docsbranch = "main"
deprecated = false
currentUrl = "https://kubernetes.io/docs/home/"
nextUrl = "https://kubernetes-io-vnext-staging.netlify.com/"

# See codenew shortcode
githubWebsiteRaw = "raw.githubusercontent.com/kubernetes/website"

# GitHub repository link for editing a page and opening issues.
github_repo = "https://github.com/kubernetes/website"

# Searching
k8s_search = false

# The following search parameters are specific to Docsy's implementation. Kubernetes implementes its own search-related partials and scripts.

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Official CVE feed bucket URL
cveFeedBucket = "https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json"

[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]

[[params.versions]]
fullversion = "v1.26.0"
version = "v1.26"
githubbranch = "v1.26.0"
docsbranch = "main"
url = "https://kubernetes.io"

[[params.versions]]
fullversion = "v1.25.5"
version = "v1.25"
githubbranch = "v1.25.5"
docsbranch = "release-1.25"
url = "https://v1-25.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.24.9"
version = "v1.24"
githubbranch = "v1.24.9"
docsbranch = "release-1.24"
url = "https://v1-24.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.23.15"
version = "v1.23"
githubbranch = "v1.23.15"
docsbranch = "release-1.23"
url = "https://v1-23.docs.kubernetes.io"

[[params.versions]]
fullversion = "v1.22.17"
version = "v1.22"
githubbranch = "v1.22.17"
docsbranch = "release-1.22"
url = "https://v1-22.docs.kubernetes.io"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Show expand/collapse icon for sidebar sections.
sidebar_menu_foldable = true
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://discuss.kubernetes.io"
	icon = "fa fa-envelope"
	desc = "Discussion and help from your fellow users"

[[params.links.user]]
	name = "Twitter"
	url = "https://twitter.com/kubernetesio"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"

[[params.links.user]]
	name = "Calendar"
	url = "https://calendar.google.com/calendar/embed?src=calendar%40kubernetes.io"
	icon = "fas fa-calendar-alt"
	desc = "Google Calendar for Kubernetes"

[[params.links.user]]
	name = "Youtube"
	url = "https://youtube.com/kubernetescommunity"
	icon = "fab fa-youtube"
	desc = "Youtube community videos"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/kubernetes/kubernetes"
	icon = "fab fa-github"
	desc = "Development takes place here!"

[[params.links.developer]]
	name = "Slack"
	url = "https://slack.k8s.io"
	icon = "fab fa-slack"
	desc = "Chat with other project developers"

[[params.links.developer]]
	name = "Contribute"
	url = "https://git.k8s.io/community/contributors/guide"
	icon = "fas fa-edit"
	desc = "Contribute to the Kubernetes website"

[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/kubernetes"
	icon = "fab fa-stack-overflow"
	desc = "Practical questions and curated answers"

# Language definitions.

[languages]
[languages.en]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName = "English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"

[languages.ru]
title = "Kubernetes"
description = "Первоклассная оркестрация контейнеров"
languageName = "Русский (Russian)"
languageNameLatinScript = "Russian"
weight = 14
contentDir = "content/ru"
languagedirection = "ltr"

[languages.ru.params]
time_format_blog = "02.01.2006"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]
